[project]
name = "site-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "idkiftheothernamesaretaken", email = "mardlion12@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django>=6.1.1",
]

[project.scripts]
site-v1 = "site_v1:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
